### ISSUE TITLE
Let player enter physical d20 rolls in response to LMRTFY requests

### ISSUE THREAD

**Issue by trdischat** [kakaroto/fvtt-module-lmrtfy#15]
LMRTFY is a big help to me in getting rolls from players and processing them, particularly when combined with minor-qol.  I have some players, however, who prefer to roll physical dice for their checks and saves.  Would it be possible to let them enter their raw roll on a physical d20 into the LMRTFY popup and let that roll override the normal behavior of letting the computer roll for them?

I was thinking that LMRTFY could include a simple input box next to the button that the player pushes to make their roll.  Here is a really ugly example of this idea:

![chrome_qYwCckafnT](https://user-images.githubusercontent.com/52774325/85097600-d983b480-b1ac-11ea-821f-11c4ed95f0df.png)

If the player enters nothing, LMRTFY would work exactly the same way it does now.  If instead the player enters the raw result of their d20 roll into the input box (e.g., the number "12" in the example above), then LMRTFY would use that number instead of rolling a d20. If LMRTFY simply substitutes the number entered by the player in place of "1d20" or "2d20kh1" in the roll formula, then all the normal modifiers and bonuses should still apply to the raw roll, just the same as they do now.  For those GMs that prefer that all rolls be automated, there could be a configuration option to disable the input box.

What do you think?

**Comment by kakaroto** [comment]
Thanks for the proposal.
I've thought about it and while I see a use for it, I'm not liking it, as it adds all sorts of complications, such as :
- Need the UI for it and a way to specify for which roll it was (if multiple checks are requested)
- Need a way to handle advantage/disadvantage as well
- Need a way to show that the user entered a value manually, otherwise it's too easy for people to cheat (i.e: only trusted players can do it, so alternatively, adding a setting to specify who you trust to have that feature)
- LMRTFY would actually need to practically implement the dnd5e system calculation for skills, because at the moment, all it does is `actor.rollSkillCheck("acr")` for example, but having the actual dice result means I'd need to find the modifier and create the formula manually rather than letting the dnd5e system create it, which may or may not be easy.

Because of that, I'm not going to be implementing this feature, sorry.
