### ISSUE TITLE
Bug/Feature? Low priority

### ISSUE THREAD

**Issue by iotech-fvtt** [kakaroto/fvtt-module-lmrtfy#4]
Had my normal 5 players last night, plus one new one (experienced player- "Tark"). At the last moment, one of my original 5 "Yrsa" pulled out of the session due to medical, leaving new player (his brother) to play his character. So, in FVTT I assigned permissions to Yrsa to Tark's player and removed Yrsa's player from permissions. 
Started game, new player could move Yrsa, see, interact with character, all normal. He could also do the same with his own character, Tark. Everything worked up until I used LMRTFY.
I'd request a roll with LMRTFY (with Controlled Characters), and he'd get prompted, but only for his Tark character.  The Yrsa character was not prompted at alll (he was using a single laptop, single browser for both and logged in on hos own account, which had Owner on both actors).

When I go off Controlled Characters and just select Tark's player, it prompts the roll and appies to both characters (as it should).

So, don't know it this is intentional, but I had to use Controlled Characters, select all EXCEPT Tark and Yrsa, prompt the roll.... then select None, change to only Tarks player, the prompt the same roll again to get both those characters.

**Comment by kakaroto** [comment]
Yeah, this is intentional. The "Controlled Characters" is not the same as "Owned Actors". You can only control one character in FVTT. You do that from the 'player configuration' screen. The scenario where someone is playing 2 characters is the whole reason why I added the 'send to specific user' rather than only having controlled characters.

The reason I'm not doing 'has permission' is because a lot of people play with every player having full permissions to everyone else. In my own game, with the number of times someone had to step out, etc.. most players can control a bunch of other player characters. Everyone also has control of the NPC following them and the shield guardian. So doing that means multiple players would get the prompt to roll for the same character.

Wanting everyone to roll without you having to switch to select different users is indeed painful. I don't have any good solutions for that. I could do 'selected tokens', but.. if you wanted to roll something, you'd have to tell everyone to select all the tokens that they can control before you send the request, which I'm sure will 50% of the time not work because someone would be too slow to select or would switch their selection instead of actually selecting both tokens, etc.. 

If you have a suggestion/solution, let me know!

**Comment by kakaroto** [comment]
Closing as discussed on discord.
If this gets reopened, an idea : 
> What do you think of "Any owner" to make anyone who owns that character to roll it. Which means a user that owns two, would roll for both, but if more than 1 player can control the same character, they will both roll for the same character.
